### ISSUE TITLE
Add possibility to define headers in contract without definition in open-api

### ISSUE THREAD

**Issue by mzielinski** [mzielinski/spring-cloud-contract-oa3#24]
Use case:

We have hidden header, which should not be displayed in open-api specification, but contract and stub should support it.

**Comment by mzielinski** [comment]
Currently it is possible in open-api define contract headers like

```
paths:
  /check-matchers/1:
    get:
      summary: Checking basic fields and matchers
      operationId: matchers

      x-contracts:
        - contractId: matchers
          name: Should verify basic file ids and matchers
          headers:
            Content-Type: application/json
            'X-SSL-Client-DN': admin@test.com

```
